version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
  # Maintain dependencies for NPM
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
