baseURL = 'https://cheatsheets.mdekort.nl/'
languageCode = 'en-us'
title = 'Cheatsheets'
enableRobotsTXT = true
relativeURLS = true

[params]
  author = 'Melvyn de Kort'
  description = 'A collection of custom cheatsheets for my personal Linux desktop setup'
  year = 2022
  sourceCode = 'https://github.com/melvyndekort/cheatsheets'

[module]
  [[module.imports]]
    path = "github.com/melvyndekort/dracula-hugo-theme"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

[[redirects]]
  from = "/"
  to = "/ffmpeg/"
  status = 302
  force = true

[[redirects]]
  from = "/index.html"
  to = "/ffmpeg/"
  status = 302
  force = true
